### ISSUE TITLE
Proposal for Improvement: Use Proper Input Types for Numeric Fields and Fix Mobile Keyboard Accessibility

### ISSUE THREAD

**Issue by alaminediallo** [JohnMwendwa/age-calculator#1]
Hello,

I propose the following improvements for the project:

1. Use the "number" type for numeric fields instead of "text" for better data precision.

2. Fix mobile keyboard accessibility by adding the "input" attribute with the value "numeric" to numeric fields.

I am ready to submit a Pull Request for these changes, or I can provide guidance if you prefer to make the changes yourself.

Thank you for considering this improvement proposal.

**Comment by JohnMwendwa** [comment]
Thanks @LamineGitHub for finding a 'bug' in my code , although I wanted it to work that way so that I may show an error when someone enters text instead of a valid number. But in the spirit of collaboration and maintaining web accessibility, feel free to do a pull request incorporating your changes.

**Comment by alaminediallo** [comment]
Thank you so much for merging my changes !

Le mer. 3 avr. 2024 à 21:54, John Mwendwa ***@***.***> a
écrit :
